/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import email from "@strapi/email/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    email: email,
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    sentry: sentry,
    "users-permissions": usersPermissions,
  },
});
